import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-daily-evv',
  templateUrl: './daily-evv.component.html',
  styleUrls: ['./daily-evv.component.sass']
})
export class DailyEvvComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  public rawData=[
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "ALLEN, PAMELA",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "392014",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "8",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "ASHLEY, ELZBIETA",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "469117",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "12",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "12",
            "MISSINGPUNCHESPERCENT": "100.0",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0.00%",
            "TEL_MANUAL_PERCENT": "100.00%",
            "Manualmissing": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "ASHLEY, MONICA",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "534632",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "2",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "100.0",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0.00%",
            "TEL_MANUAL_PERCENT": "100.00%",
            "Manualmissing": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "BRUNO, ROSA",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "330967",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "4",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "4",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "COKER, MICHAEL",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "631939",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "8",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "COMPARAN, LEANN",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "361601",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "6",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "6",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "CORBETT, LAURA",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "468600",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "6",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "6",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "ELLIOTT, ASHLEY",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "314314",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "4",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "4",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "FAIRBANKS, MARY",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "469160",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "20",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "20",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "GARCIA, ANGELICA",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "622537",
            "JOBTITLE": "Direct Support Professional",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "8",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "GERMAN DE LA ROSA, JOSEFINA",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "391287",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "12",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "12",
            "MISSINGPUNCHESPERCENT": "100.0",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0.00%",
            "TEL_MANUAL_PERCENT": "100.00%",
            "Manualmissing": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "GIL, NOEMI",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "392625",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "8",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "GUNNIP-HENRY, JASMINE",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "384133",
            "JOBTITLE": "Direct Support Professional",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "24",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "24",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "GUZMAN, LUISA",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "531634",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "4",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "4",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "HAGENSICK, JENNIFER",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "484164",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "6",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "6",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "HERRERA, JOSE",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "494220",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "12",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "12",
            "MISSINGPUNCHESPERCENT": "100.0",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0.00%",
            "TEL_MANUAL_PERCENT": "100.00%",
            "Manualmissing": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "HOLT, SEAN",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "442587",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "10",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "10",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "HOUSE, MARYAM",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "544860",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "10",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "10",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "JACKSON, JOYCE",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "477080",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "8",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "JOHNSON, MARIAH",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "541596",
            "JOBTITLE": "Home Health Aide",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "2",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "100.0",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0.00%",
            "TEL_MANUAL_PERCENT": "100.00%",
            "Manualmissing": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "JOHNSON, SASHA",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "385889",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "26",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "26",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "JONES, MELLISA",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "627202",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "6",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "6",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "KUBINA, ROBERT",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "525782",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "8",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "LEAKONA, PUATAUKANAVE",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "640324",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "20",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "20",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "LEARY, MICHELLE",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "423789",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "4",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "4",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "LOCKE, ROBERT",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "486002",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "8",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "MEJIA, NILDA",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "391261",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "12",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "12",
            "MISSINGPUNCHESPERCENT": "100.0",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0.00%",
            "TEL_MANUAL_PERCENT": "100.00%",
            "Manualmissing": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "NELSON, ROTUNDA",
            "ENTERPRISEID": "469334",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "10",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "10",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "PAREDES, AMITHY",
            "ENTERPRISEID": "336899",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "10",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "10",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "PATTERSON, LATARSHA",
            "ENTERPRISEID": "314399",
            "JOBTITLE": "Direct Support Professional",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "10",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "10",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "PORTERFIELD, SHERRELL",
            "ENTERPRISEID": "392429",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "8",
            "MISSINGPUNCHESPERCENT": "100.0",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0.00%",
            "TEL_MANUAL_PERCENT": "100.00%",
            "Manualmissing": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "PREWITT III, RONALD",
            "ENTERPRISEID": "323973",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "8",
            "MISSINGPUNCHESPERCENT": "100.0",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0.00%",
            "TEL_MANUAL_PERCENT": "100.00%",
            "Manualmissing": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "RAMSEY, APRIL",
            "ENTERPRISEID": "599881",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "28",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "28",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "RYDER, BEVERLY",
            "ENTERPRISEID": "660563",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "24",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "24",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "TADURAN, EUGENIO",
            "ENTERPRISEID": "330779",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "12",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "12",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "TALL, ERNEST",
            "ENTERPRISEID": "412795",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "14",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "14",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "TORRES, MARIA",
            "ENTERPRISEID": "647743",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "4",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "4",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "WHITE, KENDRA",
            "ENTERPRISEID": "571468",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "16",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "16",
            "TELEPHONYLANDLINEPUNCHES#": "100.0",
            "TELLANDLINEPERCENT": "0",
            "TELEPHONY_APP_PUNCHES#": "0.0",
            "TEL_APP_PERCENT": "0.00%",
            "MANUALPUNCHES": "100.00%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "STOYANOVSKI, STOIMEN",
            "ENTERPRISEID": "330884",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "34",
            "TOTALPUNCHES": "32",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "5.88",
            "TELEPHONYLANDLINEPUNCHES#": "2",
            "TELLANDLINEPERCENT": "5.9",
            "TELEPHONY_APP_PUNCHES#": "30",
            "TEL_APP_PERCENT": "88.2",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "5.88%",
            "EVVcompliant": "94.12%",
            "ComplianceStatus": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "KHOUNSAVATH, THAVONE",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "391297",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "30",
            "TOTALPUNCHES": "28",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "6.67",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "28",
            "TEL_APP_PERCENT": "93.3",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "6.67%",
            "EVVcompliant": "93.33%",
            "ComplianceStatus": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "NOGGLE, MARY",
            "ENTERPRISEID": "372262",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "22",
            "TOTALPUNCHES": "20",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "9.09",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "20",
            "TEL_APP_PERCENT": "90.9",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "9.09%",
            "EVVcompliant": "90.91%",
            "ComplianceStatus": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "NDIAYE, KEVE",
            "ENTERPRISEID": "619197",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "12",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "10",
            "TELEPHONYLANDLINEPUNCHES#": "83.3",
            "TELLANDLINEPERCENT": "2",
            "TELEPHONY_APP_PUNCHES#": "16.7",
            "TEL_APP_PERCENT": "16.67%",
            "MANUALPUNCHES": "83.33%",
            "TEL_MANUAL_PERCENT": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "VARGAS TATIS, ELIZABETH",
            "ENTERPRISEID": "442858",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "12",
            "TOTALPUNCHES": "10",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "16.67",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "10",
            "TEL_APP_PERCENT": "83.3",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "16.67%",
            "EVVcompliant": "83.33%",
            "ComplianceStatus": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "DIAZ RAMIREZ, MARIANELA",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "612234",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "10",
            "TOTALPUNCHES": "8",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "20",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "8",
            "TEL_APP_PERCENT": "80.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "20.00%",
            "EVVcompliant": "80.00%",
            "ComplianceStatus": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "HICKOK, STEVEN",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "314360",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "10",
            "TOTALPUNCHES": "8",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "20",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "8",
            "TEL_APP_PERCENT": "80.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "20.00%",
            "EVVcompliant": "80.00%",
            "ComplianceStatus": "Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "ARAGON, VERONICA",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "409950",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "25",
            "TELEPHONYLANDLINEPUNCHES#": "6",
            "TELLANDLINEPERCENT": "75.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "25.00%",
            "EVVcompliant": "75.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "DISANTO, SUSAN",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "392343",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "25",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "6",
            "TEL_APP_PERCENT": "75.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "25.00%",
            "EVVcompliant": "75.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "EVANS, JOHN",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "527436",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "12",
            "TOTALPUNCHES": "10",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "16.67",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "9",
            "TEL_APP_PERCENT": "75.0",
            "MANUALPUNCHES": "1",
            "TEL_MANUAL_PERCENT": "8.3",
            "Manualmissing": "25.00%",
            "EVVcompliant": "75.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "FURFARO, ASHLEY",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "407123",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "25",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "6",
            "TEL_APP_PERCENT": "75.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "25.00%",
            "EVVcompliant": "75.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "HERNANDEZ, EVELYN",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "469185",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "25",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "6",
            "TEL_APP_PERCENT": "75.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "25.00%",
            "EVVcompliant": "75.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "LOWE, ROHEY",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "631280",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "25",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "6",
            "TEL_APP_PERCENT": "75.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "25.00%",
            "EVVcompliant": "75.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "MABUNGA, APPLE",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "330953",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "25",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "6",
            "TEL_APP_PERCENT": "75.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "25.00%",
            "EVVcompliant": "75.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "MORRIS, OLIVER",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "412797",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "25",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "6",
            "TEL_APP_PERCENT": "75.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "25.00%",
            "EVVcompliant": "75.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "POTTS, LONDA",
            "ENTERPRISEID": "469431",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "25",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "6",
            "TEL_APP_PERCENT": "75.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "25.00%",
            "EVVcompliant": "75.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "PREWITT, ADAM",
            "ENTERPRISEID": "490677",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "25",
            "TELEPHONYLANDLINEPUNCHES#": "6",
            "TELLANDLINEPERCENT": "75.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "25.00%",
            "EVVcompliant": "75.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "TABANE, IBRA",
            "ENTERPRISEID": "618104",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "25",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "6",
            "TEL_APP_PERCENT": "75.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "25.00%",
            "EVVcompliant": "75.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "ROONEY, RACHAEL",
            "ENTERPRISEID": "626709",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "22",
            "TOTALPUNCHES": "16",
            "MISSING_PUNCHES": "6",
            "MISSINGPUNCHESPERCENT": "27.27",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "16",
            "TEL_APP_PERCENT": "72.7",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "27.27%",
            "EVVcompliant": "72.73%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "LEE, SOPHIA",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "448620",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "14",
            "TOTALPUNCHES": "10",
            "MISSING_PUNCHES": "4",
            "MISSINGPUNCHESPERCENT": "28.57",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "10",
            "TEL_APP_PERCENT": "71.4",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "28.57%",
            "EVVcompliant": "71.43%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "OCHOA, IRMA",
            "ENTERPRISEID": "330974",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "14",
            "TOTALPUNCHES": "10",
            "MISSING_PUNCHES": "4",
            "MISSINGPUNCHESPERCENT": "28.57",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "10",
            "TEL_APP_PERCENT": "71.4",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "28.57%",
            "EVVcompliant": "71.43%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "MCGREGOR, BONNIE",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "482066",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "20",
            "TOTALPUNCHES": "14",
            "MISSING_PUNCHES": "6",
            "MISSINGPUNCHESPERCENT": "30",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "14",
            "TEL_APP_PERCENT": "70.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "30.00%",
            "EVVcompliant": "70.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "MORRIS, OLIVER",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "617044",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "10",
            "TOTALPUNCHES": "7",
            "MISSING_PUNCHES": "3",
            "MISSINGPUNCHESPERCENT": "30",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "7",
            "TEL_APP_PERCENT": "70.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "30.00%",
            "EVVcompliant": "70.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "ATIIFALE, TILOMAI",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "330946",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "12",
            "TOTALPUNCHES": "8",
            "MISSING_PUNCHES": "4",
            "MISSINGPUNCHESPERCENT": "33.33",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "8",
            "TEL_APP_PERCENT": "66.7",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "33.33%",
            "EVVcompliant": "66.67%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "PONETINI, SAMOA",
            "ENTERPRISEID": "615614",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "16",
            "TOTALPUNCHES": "10",
            "MISSING_PUNCHES": "6",
            "MISSINGPUNCHESPERCENT": "37.50",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "10",
            "TEL_APP_PERCENT": "62.5",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "37.50%",
            "EVVcompliant": "62.50%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "BANKS, BARBARA",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "632925",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "10",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "4",
            "MISSINGPUNCHESPERCENT": "40",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "6",
            "TEL_APP_PERCENT": "60.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "40.00%",
            "EVVcompliant": "60.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "CRUZ, JOVANI",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "554307",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "10",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "4",
            "MISSINGPUNCHESPERCENT": "40",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "6",
            "TEL_APP_PERCENT": "60.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "40.00%",
            "EVVcompliant": "60.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "KIM, SONMI",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "584976",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "10",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "0.0",
            "MISSINGPUNCHESPERCENT": "6",
            "TELEPHONYLANDLINEPUNCHES#": "60.0",
            "TELLANDLINEPERCENT": "4",
            "TELEPHONY_APP_PUNCHES#": "40.0",
            "TEL_APP_PERCENT": "40.00%",
            "MANUALPUNCHES": "60.00%",
            "TEL_MANUAL_PERCENT": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "KING, MARTIN",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "403727",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "20",
            "TOTALPUNCHES": "12",
            "MISSING_PUNCHES": "8",
            "MISSINGPUNCHESPERCENT": "40",
            "TELEPHONYLANDLINEPUNCHES#": "11",
            "TELLANDLINEPERCENT": "55.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "1",
            "TEL_MANUAL_PERCENT": "5.0",
            "Manualmissing": "45.00%",
            "EVVcompliant": "55.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "BANCROFT, TAMMY",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "344489",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "4",
            "MISSING_PUNCHES": "50",
            "MISSINGPUNCHESPERCENT": "0",
            "TELEPHONYLANDLINEPUNCHES#": "0.0",
            "TELLANDLINEPERCENT": "4",
            "TELEPHONY_APP_PUNCHES#": "50.0",
            "TEL_APP_PERCENT": "0",
            "MANUALPUNCHES": "0.0",
            "TEL_MANUAL_PERCENT": "50.00%",
            "Manualmissing": "50.00%",
            "EVVcompliant": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "BARTEE, STEFFEN",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "632936",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "4",
            "TOTALPUNCHES": "2",
            "MISSING_PUNCHES": "50",
            "MISSINGPUNCHESPERCENT": "0",
            "TELEPHONYLANDLINEPUNCHES#": "0.0",
            "TELLANDLINEPERCENT": "2",
            "TELEPHONY_APP_PUNCHES#": "50.0",
            "TEL_APP_PERCENT": "0",
            "MANUALPUNCHES": "0.0",
            "TEL_MANUAL_PERCENT": "50.00%",
            "Manualmissing": "50.00%",
            "EVVcompliant": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "MCGREGOR, MARILYN",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "527435",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "4",
            "MISSING_PUNCHES": "50",
            "MISSINGPUNCHESPERCENT": "0",
            "TELEPHONYLANDLINEPUNCHES#": "0.0",
            "TELLANDLINEPERCENT": "4",
            "TELEPHONY_APP_PUNCHES#": "50.0",
            "TEL_APP_PERCENT": "0",
            "MANUALPUNCHES": "0.0",
            "TEL_MANUAL_PERCENT": "50.00%",
            "Manualmissing": "50.00%",
            "EVVcompliant": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "NELSON, ESHA",
            "ENTERPRISEID": "614214",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "12",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "50",
            "MISSINGPUNCHESPERCENT": "0",
            "TELEPHONYLANDLINEPUNCHES#": "0.0",
            "TELLANDLINEPERCENT": "6",
            "TELEPHONY_APP_PUNCHES#": "50.0",
            "TEL_APP_PERCENT": "0",
            "MANUALPUNCHES": "0.0",
            "TEL_MANUAL_PERCENT": "50.00%",
            "Manualmissing": "50.00%",
            "EVVcompliant": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "QUINTERO LOPEZ, YAHAIRA",
            "ENTERPRISEID": "391300",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "4",
            "MISSING_PUNCHES": "50",
            "MISSINGPUNCHESPERCENT": "0",
            "TELEPHONYLANDLINEPUNCHES#": "0.0",
            "TELLANDLINEPERCENT": "4",
            "TELEPHONY_APP_PUNCHES#": "50.0",
            "TEL_APP_PERCENT": "0",
            "MANUALPUNCHES": "0.0",
            "TEL_MANUAL_PERCENT": "50.00%",
            "Manualmissing": "50.00%",
            "EVVcompliant": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "SAETEUNE, KAREN",
            "ENTERPRISEID": "525843",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "4",
            "TOTALPUNCHES": "2",
            "MISSING_PUNCHES": "50",
            "MISSINGPUNCHESPERCENT": "0",
            "TELEPHONYLANDLINEPUNCHES#": "0.0",
            "TELLANDLINEPERCENT": "2",
            "TELEPHONY_APP_PUNCHES#": "50.0",
            "TEL_APP_PERCENT": "0",
            "MANUALPUNCHES": "0.0",
            "TEL_MANUAL_PERCENT": "50.00%",
            "Manualmissing": "50.00%",
            "EVVcompliant": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "THOMPSON, JESSICA",
            "ENTERPRISEID": "421709",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "4",
            "TOTALPUNCHES": "2",
            "MISSING_PUNCHES": "50",
            "MISSINGPUNCHESPERCENT": "0",
            "TELEPHONYLANDLINEPUNCHES#": "0.0",
            "TELLANDLINEPERCENT": "2",
            "TELEPHONY_APP_PUNCHES#": "50.0",
            "TEL_APP_PERCENT": "0",
            "MANUALPUNCHES": "0.0",
            "TEL_MANUAL_PERCENT": "50.00%",
            "Manualmissing": "50.00%",
            "EVVcompliant": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "ESCALANTE, ELSA",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "392019",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "10",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "4",
            "MISSINGPUNCHESPERCENT": "40",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "4",
            "TEL_APP_PERCENT": "40.0",
            "MANUALPUNCHES": "2",
            "TEL_MANUAL_PERCENT": "20.0",
            "Manualmissing": "60.00%",
            "EVVcompliant": "40.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "PETERSON, GERALDA",
            "ENTERPRISEID": "330838",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "20",
            "TOTALPUNCHES": "12",
            "MISSING_PUNCHES": "8",
            "MISSINGPUNCHESPERCENT": "40",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "8",
            "TEL_APP_PERCENT": "40.0",
            "MANUALPUNCHES": "4",
            "TEL_MANUAL_PERCENT": "20.0",
            "Manualmissing": "60.00%",
            "EVVcompliant": "40.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "JOHNSON-SHADBOLT, SHIRLEY",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "414835",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "16",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "10",
            "MISSINGPUNCHESPERCENT": "62.50",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "6",
            "TEL_APP_PERCENT": "37.5",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "62.50%",
            "EVVcompliant": "37.50%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "WILSON, ANNETTE",
            "ENTERPRISEID": "616927",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "6",
            "TOTALPUNCHES": "2",
            "MISSING_PUNCHES": "4",
            "MISSINGPUNCHESPERCENT": "66.67",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "2",
            "TEL_APP_PERCENT": "33.3",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "66.67%",
            "EVVcompliant": "33.33%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "FEDOR, TONYA",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "647975",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "16",
            "TOTALPUNCHES": "6",
            "MISSING_PUNCHES": "10",
            "MISSINGPUNCHESPERCENT": "62.50",
            "TELEPHONYLANDLINEPUNCHES#": "4",
            "TELLANDLINEPERCENT": "25.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "2",
            "TEL_MANUAL_PERCENT": "12.5",
            "Manualmissing": "75.00%",
            "EVVcompliant": "25.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "KUEHN, KALEB",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "403297",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "2",
            "MISSING_PUNCHES": "6",
            "MISSINGPUNCHESPERCENT": "75",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "2",
            "TEL_APP_PERCENT": "25.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "75.00%",
            "EVVcompliant": "25.00%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "EVANS, ASHLEY",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "490671",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "12",
            "TOTALPUNCHES": "2",
            "MISSING_PUNCHES": "10",
            "MISSINGPUNCHESPERCENT": "83.33",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "2",
            "TEL_APP_PERCENT": "16.7",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "83.33%",
            "EVVcompliant": "16.67%",
            "ComplianceStatus": "Partial Compliance, but below threshold"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "BASS, TONYA",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "314666",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "2",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "100",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "BAUGH, ADONUS",
            "ENTERPRISEID": "585060",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "2",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "100",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "BOWSER, DAISY",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "469129",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "10",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "10",
            "MISSINGPUNCHESPERCENT": "100",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "BROWN, MARGARET",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "619238",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "18",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "18",
            "MISSINGPUNCHESPERCENT": "100",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "CARTER, TANIKA",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "315280",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "8",
            "MISSINGPUNCHESPERCENT": "100",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "EVANS, DIANE",
            "DCSCOORDINATOR": "Eaton, Shae",
            "ENTERPRISEID": "527676",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "12",
            "TOTALPUNCHES": "2",
            "MISSING_PUNCHES": "10",
            "MISSINGPUNCHESPERCENT": "83.33",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "2",
            "TEL_MANUAL_PERCENT": "16.7",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "HERNANDEZ, NOEMI",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "649292",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "24",
            "TOTALPUNCHES": "4",
            "MISSING_PUNCHES": "20",
            "MISSINGPUNCHESPERCENT": "83.33",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "4",
            "TEL_MANUAL_PERCENT": "16.7",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "HUMBLE, BRENDA",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "616314",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "8",
            "MISSINGPUNCHESPERCENT": "100",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "JIMENEZ BAEZ, ROBELY",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "571535",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "4",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "4",
            "MISSINGPUNCHESPERCENT": "100",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "JONES, TANYA",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "407773",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "4",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "4",
            "MISSINGPUNCHESPERCENT": "100",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "KNOX, VALISHIA",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "391298",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "8",
            "MISSINGPUNCHESPERCENT": "100",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "LOCKHART, ALESHIA",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "488055",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "8",
            "MISSINGPUNCHESPERCENT": "100",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "LUDDINGTON, SHIRLEY",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "330432",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "2",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "2",
            "MISSINGPUNCHESPERCENT": "100",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "MILLER, KIMBERLY",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "392576",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "6",
            "TOTALPUNCHES": "2",
            "MISSING_PUNCHES": "4",
            "MISSINGPUNCHESPERCENT": "66.67",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "2",
            "TEL_MANUAL_PERCENT": "33.3",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "MORENO, MARY",
            "DCSCOORDINATOR": "Banks, Kenosha",
            "ENTERPRISEID": "330796",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "8",
            "MISSINGPUNCHESPERCENT": "100",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "RIVAS DE REYES, KATERI",
            "ENTERPRISEID": "612158",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "6",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "6",
            "MISSINGPUNCHESPERCENT": "100",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "SHTURM, DINAH",
            "ENTERPRISEID": "656634",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "6",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "6",
            "MISSINGPUNCHESPERCENT": "100",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        },
        {
            "RVP": "PACIFIC",
            "ED": "ED: RCHC ALASKA",
            "BR: RCHC AK ANCHORAGE": "BR: RCHC AK ANCHORAGE",
            "DCSHOMESITE": "50007",
            "SITENAME": "PPC AK ANCHORAGE STATE FUNDED",
            "DCSNAME": "THUNGC, STEVEN",
            "ENTERPRISEID": "330332",
            "JOBTITLE": "Caregiver",
            "PERIOD": "May ",
            "TOTALEXPECTEDPUNCHES": "8",
            "TOTALPUNCHES": "0",
            "MISSING_PUNCHES": "8",
            "MISSINGPUNCHESPERCENT": "100",
            "TELEPHONYLANDLINEPUNCHES#": "0",
            "TELLANDLINEPERCENT": "0.0",
            "TELEPHONY_APP_PUNCHES#": "0",
            "TEL_APP_PERCENT": "0.0",
            "MANUALPUNCHES": "0",
            "TEL_MANUAL_PERCENT": "0.0",
            "Manualmissing": "100.00%",
            "EVVcompliant": "0.00%",
            "ComplianceStatus": "Non Compliant"
        }
    ]


}
